/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.ticketapp.configserver;


import org.junit.jupiter.api.Test;

import static org.junit.jupiter.api.Assertions.assertTrue;

public class AppTest {
    @Test
    public void appTest() {
        assertTrue(true);
    }
}
