/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.movieTicketService.userservice;


import org.junit.Test;

public class UserServiceMainTest {
    @Test
    public void mainTest() {}
}
