/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.ticketapp.userservice;


import org.junit.jupiter.api.Test;
import org.springframework.boot.test.context.SpringBootTest;

@SpringBootTest
public class UserServiceMainTest {
    @Test
    public void contextLoads() {}
}
