/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.movieTicketService.configserver;

import org.junit.Test;
import static org.junit.Assert.*;

public class AppTest {
    @Test public void appTest() {}
}
