server:
  port: 8888

spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/akarshippili/TicketApp-Configuration
          default-label: main
          clone-on-start: true