/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.bookmyshow.userservice;

import org.junit.jupiter.api.Test;
import org.springframework.util.Assert;

import static org.junit.jupiter.api.Assertions.assertNotNull;

public class UserServiceMainTest {
    @Test
    public void mainTest() {
        UserServiceMain classUnderTest = new UserServiceMain();
        assertNotNull(classUnderTest);
    }
}
