# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-gradle

name: Java CI with Gradle

on:
  push:
    branches:
      - 'main'
      - 'feature/location-service-docker-image-actions'

  pull_request:
    types:
      - closed
    branches:
      - 'main'

permissions:
  contents: read

jobs:
  
  build-and-publish:
    runs-on: ubuntu-latest

    steps:

    - name: git checkout
      uses: actions/checkout@v3
    
    - name: Set up JDK 16
      uses: actions/setup-java@v3
      with:
        java-version: '16'
        distribution: 'temurin'

    - name: cd into user-service
      run: |
          pwd
          ls -a .
          cd ./user-service
          pwd
          ls -a .
      shell: bash
        
    - name: Build with Gradle [user-service]
      uses: gradle/gradle-build-action@67421db6bd0bf253fb4bd25b31ebb98943c375e1
      with:
        arguments: build
    
    - name: cd into build/libs directory
      run: |
          pwd
          ls -a .
          cd ./build/libs
          pwd
          ls -a .
      shell: bash
    
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    
    - name: Build and push Docker images [user-service]
      uses: docker/build-push-action@v3.2.0
      with:
        context: /home/runner/work/TicketApp/TicketApp/user-service        
        push: true
        tags: akarshippili/user-service:latest
